trigger:
  - master

pool:
  vmImage: ubuntu-latest

variables:
 - group: arm-variables


resources:
- repo: self

stages:
- stage: CI_Infra_Deploy
  displayName: Infra Deploy
  jobs:
  - job: azcli
    displayName: azcli Job
    steps:
    - task: AzureCLI@2
      displayName: 'Deploy Resource Group'
      inputs:
        azureSubscription: $(AzureResourceManagerConnection)
        scriptType: bash
        scriptLocation: inlineScript
        addSpnToEnvironment: true
        inlineScript: |
          #!/bin/bash
          az group create -l "$Location" -n "$ResourceGroupName"
          az aks create -g "$ResourceGroupName" -n "$K8sClusterName" --enable-managed-identity --node-count 1 --generate-ssh-keys
          