trigger:
  - master

pool:
  vmImage: ubuntu-latest

variables:
 - group: arm-variables


resources:
- repo: self

stages:
- stage: CI_Infra_Deploy
  displayName: Infra Deploy
  jobs:
  - job: azcli
    displayName: azcli Job
    steps:
    - task: AzureCLI@2
      displayName: 'Deploy Resource Group'
      inputs:
        azureSubscription: $(AzureResourceManagerConnection)
        scriptType: bash
        scriptLocation: inlineScript
        addSpnToEnvironment: true
        inlineScript: |
          #!/bin/bash

          $Location1 = "$(Location)"
          $ResourceGroupName1 = "$(ResourceGroupName)"
          $K8sClusterName1 = "$(K8sClusterName)"
          
          az group create -l $Location1 -n $ResourceGroupName1
          az aks create -g $ResourceGroupName1 -n $K8sClusterName1 --enable-managed-identity --node-count 1 --generate-ssh-keys
          