trigger:
- master

#variables:
#  global_variable: value    # this is available to all jobs

jobs:
- job: terraform_deployment
  pool:
    vmImage: ubuntu-latest
  variables:
    az_region:  "southindia"
    resource_group_name: "aks-rg"
    subscription: "b798c28b-e334-4ecf-b338-ec314ced3616"
    key_vault_name: "akskeyvault524"
    sa_prefix: "aksstg52420331"
    sa_container_name: "stgcontainer"
    tfstateFile: terraform.tfstate

  steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'arm-svc-connection' #replace with your service connection - azure resource manager service principal
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az group create -n $(resource_group_name) -l $(az_region)
        VAULT_ID=$(az keyvault create --name "$(key_vault_name)" --resource-group "$(resource_group_name)" --location "$(az_region)" --query "id" -o tsv)
        az storage account create --resource-group $(resource_group_name) --name "$(sa_prefix)" --sku Standard_LRS --encryption-services blob
        az storage container create --name $(sa_container_name) --account-name "$(sa_prefix)" --auth-mode login

  - task: TerraformInstaller@0
    displayName: Terraform Installation
    inputs:
      terraformVersion: 'latest'

  - task: TerraformTaskV3@3
    displayName: Terraform Init
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/Infra-Pipeline/Terraform2/config-tf'
      backendServiceArm: 'arm-svc-connection'
      backendAzureRmResourceGroupName: '$(resource_group_name)'
      backendAzureRmStorageAccountName: '$(sa_prefix)'
      backendAzureRmContainerName: '$(sa_container_name)'
      backendAzureRmKey: '$(tfstateFile)'

  - task: TerraformTaskV3@3
    displayName: Terraform Plan
    inputs:
      provider: 'azurerm'
      command: 'plan'
      workingDirectory: '$(System.DefaultWorkingDirectory)/Infra-Pipeline/Terraform2/config-tf'
      commandOptions: '-out=tfplan'
      environmentServiceNameAzureRM: 'arm-svc-connection'

  - task: TerraformTaskV3@3
    displayName: Terraform Apply
    inputs:
      provider: 'azurerm'
      command: 'apply'
      workingDirectory: '$(System.DefaultWorkingDirectory)/Infra-Pipeline/Terraform2/config-tf'
      commandOptions: 'tfplan'
      environmentServiceNameAzureRM: 'arm-svc-connection'

